#!/bin/bash

## Loading logger
export HS_HOME=/opt/home_services/src/home_services
source $HS_HOME/src/hs_utils/setup/hs_bash_logs.bash

# Sourcing ROS environment
export ROS_LOG_DIR=/opt/home_services/data/logs
source $HS_HOME/devel/setup.bash

# Starting band search
info "Unpausing download"
rostopic pub /download_torrent/move_state torrent_search/State "header: auto
state: 'remove_pause'" -1;
