#!/bin/bash

## Loading logger
export HS_HOME=/opt/home_services/src/home_services
source $HS_HOME/src/hs_utils/setup/hs_bash_logs.bash

# Sourcing ROS environment
export ROS_LOG_DIR=/opt/home_services/data/logs
source $HS_HOME/devel/setup.bash
source $HS_HOME/src/torrent_search/setup/hs_api_keys.bash

# Starting band search
info "Starting yts finder"
roslaunch torrent_search download_torrent.launch

