#!/bin/bash

## Loading logger
export HS_HOME=/opt/home_services/src/home_services
source $HS_HOME/src/hs_utils/setup/hs_bash_logs.bash

# Sourcing ROS environment
export ROS_LOG_DIR=/opt/home_services/data/logs
source $HS_HOME/devel/setup.bash

## Check if argument was provided
export SEED_VALUE=$1
if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    SEED_VALUE=1900
fi

# Starting band search
info "Triggering YTS crawler"
rostopic pub /yts_finder/trigger_download torrent_search/TriggerDownload "header: auto
seeds: $SEED_VALUE
search_type: 102" -1;
